VIPGroups:
  - "teste"

DAYS: "dias"
HOURS: "horas"
MINUTES: "minutos"

VIP_PERMISSION: "viputilities.vip"

ExpiryVIPMessage: "&e[VIP&6Utilities] &aO seu vip vai expirar em {days}, {hours}, {minutes}"
ExpiryVIPOtherMessage: "&e[VIP&6Utilities] &aO VIP de {player} vai expirar em {days}, {hours}, {minutes}"

ErrorSpecifyPlayerGroupDaysAdd: "&e[VIP&6Utilities] &cVocê deve especificar o jogador, grupo e dias para adicionar!"
ErrorSpecifyPlayerGroupRemove: "&e[VIP&6Utilities] &cVocê deve especificar o jogador e o grupo para remover!"
ErrorSpecifyGroup: "&e[VIP&6Utilities] &cVocê deve especificar o grupo."
ErrorSpecifyDays: "&e[VIP&6Utilities] &cVocê deve especificar os dias."
ErrorNoPermission: "&e[VIP&6Utilities] &cVocê não possui permissão para isso."
ErrorInvalidGroupVIP: "&e[VIP&6Utilities] &cO grupo vip inserido é inválido, adicione na configuração!"
ErrorPlayerNotVIP: "&e[VIP&6Utilities] &cO jogador não é VIP."

SuccessAdded: "&e[VIP&6Utilities] &aVocê adicionou o jogador ao VIP com sucesso!"
SuccessRemoved: "&e[VIP&6Utilities] &aVocê retirou o VIP do jogador com sucesso!"

BroadcastMessage: "&e[VIP&6Utilities] &aO jogador {player} acaba de ter seu VIP {group} ativado!"

ChannelID: "913131412343898112"
AnnounceNewVipMessage: ":star: Notificação de VIP\n\n**O jogador {player} acaba de ter seu VIP {group} ativado com sucesso!**\n\n`Parabéns, aproveite!` :tada: \n\n`Compre você também`: <#920736042913509426> :fire:"